# Generated by Django 3.0 on 2021-05-26 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jwtauth', '0003_auto_20210525_1924'),
        ('panic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cur_lat', models.CharField(max_length=120)),
                ('cur_lng', models.CharField(max_length=120)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panic_normal', to='jwtauth.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='PanicNormal',
        ),
    ]
