# Generated by Django 3.0 on 2021-05-25 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwtauth', '0002_auto_20210525_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency', to='jwtauth.Profile'),
        ),
    ]
