# Generated by Django 3.0 on 2021-05-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtauth', '0003_auto_20210525_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='profile',
            name='nik',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
