# Generated by Django 3.0 on 2021-05-26 08:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jwtauth', '0003_auto_20210525_1924'),
        ('forum', '0003_auto_20210526_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('descriprtion', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('cur_lat', models.CharField(max_length=120)),
                ('cur_lng', models.CharField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.Category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jwtauth.Profile')),
            ],
        ),
    ]
