# Generated by Django 3.0 on 2021-05-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210526_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='descriprtion',
            new_name='description',
        ),
    ]
