# Generated by Django 3.0 on 2021-05-26 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwtauth', '0003_auto_20210525_1924'),
        ('forum', '0002_auto_20210525_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcers', to='jwtauth.Profile'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='mark_as_read',
            field=models.ManyToManyField(related_name='announcements', to='jwtauth.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='jwtauth.Profile'),
        ),
    ]
